import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import clsx from "clsx";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={clsx(
                    inter.className,
                    "flex h-screen w-screen items-center justify-center"
                )}
            >
                {children}
            </body>
        </html>
    );
}
